export const IconJson = {
  "ep:": [
    "add-location",
    "aim",
    "alarm-clock",
    "apple",
    "arrow-down",
    "arrow-down-bold",
    "arrow-left",
    "arrow-left-bold",
    "arrow-right",
    "arrow-right-bold",
    "arrow-up",
    "arrow-up-bold",
    "avatar",
    "back",
    "baseball",
    "basketball",
    "bell",
    "bell-filled",
    "bicycle",
    "bottom",
    "bottom-left",
    "bottom-right",
    "bowl",
    "box",
    "briefcase",
    "brush",
    "brush-filled",
    "burger",
    "calendar",
    "camera",
    "camera-filled",
    "caret-bottom",
    "caret-left",
    "caret-right",
    "caret-top",
    "cellphone",
    "chat-dot-round",
    "chat-dot-square",
    "chat-line-round",
    "chat-line-square",
    "chat-round",
    "chat-square",
    "check",
    "checked",
    "cherry",
    "chicken",
    "circle-check",
    "circle-check-filled",
    "circle-close",
    "circle-close-filled",
    "circle-plus",
    "circle-plus-filled",
    "clock",
    "close",
    "close-bold",
    "cloudy",
    "coffee",
    "coffee-cup",
    "coin",
    "cold-drink",
    "collection",
    "collection-tag",
    "comment",
    "compass",
    "connection",
    "coordinate",
    "copy-document",
    "cpu",
    "credit-card",
    "crop",
    "d-arrow-left",
    "d-arrow-right",
    "d-caret",
    "data-analysis",
    "data-board",
    "data-line",
    "delete",
    "delete-filled",
    "delete-location",
    "dessert",
    "discount",
    "dish",
    "dish-dot",
    "document",
    "document-add",
    "document-checked",
    "document-copy",
    "document-delete",
    "document-remove",
    "download",
    "drizzling",
    "edit",
    "edit-pen",
    "eleme",
    "eleme-filled",
    "expand",
    "failed",
    "female",
    "files",
    "film",
    "filter",
    "finished",
    "first-aid-kit",
    "flag",
    "fold",
    "folder",
    "folder-add",
    "folder-checked",
    "folder-delete",
    "folder-opened",
    "folder-remove",
    "food",
    "football",
    "fork-spoon",
    "fries",
    "full-screen",
    "goblet",
    "goblet-full",
    "goblet-square",
    "goblet-square-full",
    "goods",
    "goods-filled",
    "grape",
    "grid",
    "guide",
    "headset",
    "help",
    "help-filled",
    "histogram",
    "home-filled",
    "hot-water",
    "house",
    "ice-cream",
    "ice-cream-round",
    "ice-cream-square",
    "ice-drink",
    "ice-tea",
    "info-filled",
    "iphone",
    "key",
    "knife-fork",
    "lightning",
    "link",
    "list",
    "loading",
    "location",
    "location-filled",
    "location-information",
    "lock",
    "lollipop",
    "magic-stick",
    "magnet",
    "male",
    "management",
    "map-location",
    "medal",
    "menu",
    "message",
    "message-box",
    "mic",
    "microphone",
    "milk-tea",
    "minus",
    "money",
    "monitor",
    "moon",
    "moon-night",
    "more",
    "more-filled",
    "mostly-cloudy",
    "mouse",
    "mug",
    "mute",
    "mute-notification",
    "no-smoking",
    "notebook",
    "notification",
    "odometer",
    "office-building",
    "open",
    "operation",
    "opportunity",
    "orange",
    "paperclip",
    "partly-cloudy",
    "pear",
    "phone",
    "phone-filled",
    "picture",
    "picture-filled",
    "picture-rounded",
    "pie-chart",
    "place",
    "platform",
    "plus",
    "pointer",
    "position",
    "postcard",
    "pouring",
    "present",
    "price-tag",
    "printer",
    "promotion",
    "question-filled",
    "rank",
    "reading",
    "reading-lamp",
    "refresh",
    "refresh-left",
    "refresh-right",
    "refrigerator",
    "remove",
    "remove-filled",
    "right",
    "scale-to-original",
    "school",
    "scissor",
    "search",
    "select",
    "sell",
    "semi-select",
    "service",
    "set-up",
    "setting",
    "share",
    "ship",
    "shop",
    "shopping-bag",
    "shopping-cart",
    "shopping-cart-full",
    "smoking",
    "soccer",
    "sold-out",
    "sort",
    "sort-down",
    "sort-up",
    "stamp",
    "star",
    "star-filled",
    "stopwatch",
    "success-filled",
    "sugar",
    "suitcase",
    "sunny",
    "sunrise",
    "sunset",
    "switch",
    "switch-button",
    "takeaway-box",
    "ticket",
    "tickets",
    "timer",
    "toilet-paper",
    "tools",
    "top",
    "top-left",
    "top-right",
    "trend-charts",
    "trophy",
    "turn-off",
    "umbrella",
    "unlock",
    "upload",
    "upload-filled",
    "user",
    "user-filled",
    "van",
    "video-camera",
    "video-camera-filled",
    "video-pause",
    "video-play",
    "view",
    "wallet",
    "wallet-filled",
    "warning",
    "warning-filled",
    "watch",
    "watermelon",
    "wind-power",
    "zoom-in",
    "zoom-out",
  ],
  "fa6-solid:": [
    // --- 客服 (Customer Service) ---
    "headset", // 客服/呼叫中心 (最经典)
    "comment-dots", // 会话/在线聊天
    "user-tie", // 客服专员
    "circle-question", // 帮助中心/FAQ

    // --- 日志 (Log/Audit) ---
    "file-lines", // 系统日志/列表
    "clock-rotate-left", // 操作记录/审计回溯
    "clipboard-list", // 运行日志
    "bug", // 错误日志

    // --- 素材 (Material/Assets) ---
    "photo-film", // 多媒体素材 (图片+视频)
    "folder-open", // 素材库/文件夹
    "clapperboard", // 视频素材
    "image", // 图片管理
    "cloud-arrow-up", // 素材上传

    // --- 营销 (Marketing) ---
    "bullhorn", // 营销活动/公告
    "envelope-open-text", // 邮件营销/推文
    "rocket", // 推广/引流
    "share-nodes", // 分享/裂变

    // --- 退款 (Refund/Order) ---
    "money-bill-transfer", // 退款/资金流向 (非常精准)
    "hand-holding-dollar", // 退款处理/售后
    "cart-arrow-down", // 订单售后
    "rotate-left", // 撤回/返还

    // --- 数据 & 数据分析 (Data & Analysis) ---
    "chart-pie", // 数据占比/分布
    "chart-line", // 趋势分析
    "chart-column", // 柱状图对比
    "database", // 基础数据/数仓
    "magnifying-glass-chart", // 深度数据挖掘

    // --- 系统设置 (System Settings) ---
    "gear", // 基础设置
    "gears", // 模块配置/集成
    "sliders", // 参数调优
    "shield-halved", // 安全设置/权限

    // --- 优惠券 (Coupons/Promotion) ---
    "ticket-simple", // 优惠券 (FA6 新版，更简洁)
    "tags", // 促销标签
    "gift", // 礼品/奖品
    "percent", // 折扣率
  ],

  "fa6-brands:": [
    "500px",
    "amazon",
    "android",
    "angellist",
    "apple",
    "behance",
    "bitbucket",
    "bitcoin",
    "bluetooth",
    "chrome",
    "codepen",
    "css3",
    "delicious",
    "deviantart",
    "digg",
    "dropbox",
    "drupal",
    "edge",
    "facebook",
    "firefox",
    "fonticons",
    "fort-awesome",
    "foursquare",
    "get-pocket",
    "git",
    "github",
    "gitlab",
    "google",
    "google-plus",
    "html5",
    "instagram",
    "internet-explorer",
    "jsfiddle",
    "linkedin",
    "linux",
    "maxcdn",
    "medium",
    "opera",
    "pagelines",
    "paypal",
    "pinterest",
    "qq",
    "rebel",
    "reddit",
    "skype",
    "slack",
    "slideshare",
    "snapchat",
    "soundcloud",
    "spotify",
    "stack-exchange",
    "stack-overflow",
    "steam",
    "tencent-weibo",
    "trello",
    "tumblr",
    "twitch",
    "twitter",
    "usb",
    "viacoin",
    "vimeo",
    "vine",
    "vk",
    "wechat",
    "weibo",
    "whatsapp",
    "wikipedia-w",
    "windows",
    "wordpress",
    "xing",
    "yahoo",
    "yelp",
    "youtube",
  ],
};
